language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch

sudo: false
os:
  - linux
  - osx

# command to install dependencies
install: "pip install -r requirements-build.txt"
# command to run tests
script:
  - make test-all # Run tests
  - make build	  # Build pex package
  - make install  # Install non-pex package with pip
  